dataset: humaneva
nz: 128
t_his: 15
t_pred: 60
lambda_v: 1000
beta: 0.01
vae_specs:
  rnn_type: gru
  x_birnn: false
  e_birnn: false
  use_drnn_mlp: true
vae_lr: 1.e-3
batch_size: 64
num_vae_epoch: 500
num_vae_epoch_fix: 100
num_vae_data_sample: 1000

nk: 10
dlow_batch_size: 64
d_scale: 20
lambda_j: 50
lambda_recon: 2.0
dlow_lr: 1.e-4
dlow_specs:
  model_name: NFDiag
  rnn_type: gru
  nh_mlp: [1024, 512]
  x_birnn: false
num_dlow_epoch: 500
num_dlow_epoch_fix: 100
num_dlow_data_sample: 1000

nf_specs:
  model_name: NF
  hidden_dim: 128
  num_flow_layer: 3
  num_ds_layer: 2
vae_lr: 1.e-2
batch_size: 4096
num_vae_epoch: 25
num_vae_epoch_fix: 5
num_vae_data_sample: 200000
con_hidden_dim: 128
data_hidden_dim: 128
normalize_data: False
save_model_interval: 1
